### ISSUE TITLE
HAL camera uri command-line help feature

### ISSUE THREAD

**Issue by Algomorph** [arpg/HAL#102]
1) How do I format the full uri for ProtoReaderDriver?
```./SensorViewer -cam log:<path_to_file>``` doesn't seem to work with relative or absolute paths. What's missing?

2) It would be nice for HAL to auto-generate a help-file string about camera URIs during compilation, which could then be flushed to the console (e.g. using the "-h" or "--help" flags) by any command-line client application. SensorViewer could serve as an example. This would mean that each of the Factory classes would somehow automatically add to the help string, i.e. if a certain driver is not compiled, its reference would not appear in the help string.

**Comment by Algomorph** [comment]
For (1), never mind, figured it out:
```./SensorViewer -cam log://<path_to_file>```

**Comment by crheckman** [comment]
1) `./SensorViewer -cam log://[path_to_file]` should suffice --- if we're talking past one another, could you provide me with a full copy-paste of your command line input and output when you try to run the command?

2) We certainly need better documentation. Right now only [one line in the Documentation](https://github.com/arpg/Documentation/tree/master/Installation) has mention of SensorViewer. We could start by building out the documentation in the repo and then potentially moving to a more stratified command-line help menu as you discuss. In the meantime, feel free to submit PRs in places you like and we'll be quick about merging them.

Please write back with how 1) turned out for you.

**Comment by crheckman** [comment]
Alright, glad to have that sorted out.

In the meantime, we'll try and do better about documenting everything.
