### ISSUE TITLE
Join driver does not work with cameras having multiple streams

### ISSUE THREAD

**Issue by JStech** [arpg/HAL#134]
With two Ximea cameras plugged in, `SensorViewer -cam 'ximea://'` shows two video streams. However, `SensorViewer -cam 'join://ximea://'` shows only a black screen.

**Comment by mcguire-steve** [comment]
Investigating, 'join://ximea:[id0=33470951,mode=RGB24]//&opencv://' yields two images - suggesting the Ximea driver is not behaving in a manner compatible with the Join driver when using multiple cameras

**Comment by mcguire-steve** [comment]
On further investigation, the Join driver makes the implicit assumption that the number of camera systems is equal to the number of images, otherwise returning false from the Capture() call. This behavior yields a black screen. Corrected in branch fixes/join_multistream, awaiting approval of pull request

**Comment by mcguire-steve** [comment]
![joindriver_hal_fix](https://cloud.githubusercontent.com/assets/5855021/18030861/f5278596-6c7c-11e6-9cfa-42fdca88eddd.png)

**Comment by crheckman** [comment]
@jstech please test this when you get the chance.

**Comment by JStech** [comment]
Will do first thing tomorrow. Thanks!

**Comment by JStech** [comment]
All good. Thanks!
