### ISSUE TITLE
RealSense IMU

### ISSUE THREAD

**Issue by barnjamin** [arpg/HAL#158]
Hello, Thank you for the great Open Source Contributions.

I'd like to try using Vicalib to calibrate the RealSense D435i Camera.  I see there is no IMU driver available for this device and I'm not sure it is possible to fulfill the interface for the separate streams.

I may try to write a video file and and csv with IMU readings then feed that in but I'm not sure that is reasonable either.  

Any recommendations? 

Thanks!

**Comment by crheckman** [comment]
Thanks for your interest. We are considering writing a new class of device
that captures both camera and IMU data, but the workaround you describe
should be fine too since our FileReader driver can handle image files and
CSV IMU data separately. You might also consider using the ROS driver for
camera and IMU that we have if you use ROS.

**Comment by barnjamin** [comment]
Great, thanks!
